### ISSUE TITLE
need help in guidance on how to open the website properly locally

### ISSUE THREAD

**Issue by chirag127** [naman153/TheFabricStore#1]
**Issue URL** : file:///D:/Downloads/TheFabricStore-main/main/templates/main/feedback.html

the extracted folder of the repo is in the D:/Downloads

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/76880977/135318850-705b2a26-b82b-42ac-9b31-9b20eaa7f34b.png)

</details><br/>

**Comment by naman153** [comment]
Hey this website is live due to which it can't be opened locally now but you can check  https://thefabricstore.herokuapp.com
